import fs from 'fs/promises';

const REG_LICENSE_FILE = /license/i;
const REG_ESCAPE = /`/gm;
const COMPONENT = `
// DO NOT EDIT
// AUTO GENERATED BY scripts/genrateLicenses.js
import React from 'react';

import LicenseCard from './LicenseCard.js';

export default function Builds() {
    return (
        <>
            __STRINGS__
        </>
    );
}
`;

async function main() {
    const START = Date.now();
    const pkgPath = new URL('../../package.json', import.meta.url);
    const modulesPath = new URL('../../node_modules/', import.meta.url);
    const pkg = await fs.readFile(pkgPath, 'utf-8');
    const { dependencies } = JSON.parse(pkg);
    const deps = Object.keys(dependencies);
    const licenses = [];
    const findLicenses = async (i) => {
        if (i >= deps.length) {
            return;
        }
        const pkgName = deps[i];
        const mPath = new URL(`${pkgName}/`, modulesPath);
        const files = await fs.readdir(mPath);
        const mPkg = await fs.readFile(new URL('./package.json', mPath), 'utf-8');
        const { license: type } = JSON.parse(mPkg);
        const licenseTxt = files.find((v) => REG_LICENSE_FILE.test(v));
        const lc = {
            name: pkgName,
            type,
        };
        if (licenseTxt) {
            const lcPath = new URL(licenseTxt, mPath);
            const content = await fs.readFile(lcPath, 'utf-8');
            lc.content = content.replace(REG_ESCAPE, '');
        }
        licenses.push(lc);
        await findLicenses(i + 1);
    };

    await findLicenses(0);
    const strComponents = licenses.map(component);
    const outputPath = new URL('../src/pages/about/copyrights/Builds.js', import.meta.url);
    const fileContent = COMPONENT.replace('__STRINGS__', strComponents.join(''));

    await fs.writeFile(outputPath, fileContent);
    console.log('Done %dms.', parseInt(Date.now() - START, 10));
}

function component(lc) {
    const { name, type, content } = lc;
    return `
        <LicenseCard name="${name}" type="${type || ''}">
            {\`${content || ''}\`}
        </LicenseCard>
    `.trim();
}

main();
